### ISSUE TITLE
引用到vue项目中无法使用

### ISSUE THREAD

**Issue by lwlcurry1996** [nianzx/vue-linejs#6]
您好,我按照你的方法引入到vue项目中,但是无法使用,
![image](https://user-images.githubusercontent.com/65674824/103750919-72432a00-5042-11eb-8fc7-f5c62b406246.png)

**Comment by nianzx** [comment]
@lwlcurry1996  您好，感谢您的反馈，我这边测试了下是可以正常使用的，能否请您提供更详细的调用情况
